name: Semver Release Action Action
description: "A GitHub Action to create a semver release for an action"
branding:
  icon: "git-commit"
  color: "gray-dark"
author: Makeshift

inputs:
  readme:
    description: "The path to the readme file"
    default: "Readme.md"
  files:
    description: "A newline-delimited list of files to include in the release"
    default: |
      action.yml
      *.sh
      Readme.md

runs:
  using: composite
  steps:
    - name: Set Commit Description
      id: commit_desc
      shell: bash
      run: |
        echo "::set-output name=value::$(git log -1 --pretty=%B)"

    - name: Update Readme
      uses: npalm/action-docs-action@v1.4.0
      with:
        readme: ${{ inputs.readme }}

    - uses: stefanzweifel/git-auto-commit-action@v4.15.4
      id: auto-commit-action
      with:
        commit_message: "[no ci] (docs) ${{ steps.commit_desc.outputs.value }}"

    - name: Checkout if new commit created
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.auto-commit-action.outputs.commit_hash }}

    - name: Regex match on commit
      uses: sunil-samtani/regex-action@v2
      id: bump
      with:
        search_string: ${{ steps.commit_desc.outputs.value }}
        regex_pattern: "major|minor|patch"

    - name: Increment Semver
      uses: Makeshift/increment-semver@v0.1.6
      id: semver
      with:
        version-level: ${{ contains(fromJson('["major", "minor", "patch"]'), steps.bump.outputs.first_match) && steps.bump.outputs.first_match || 'patch' }}

    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: ${{ steps.semver.outputs.version }}
        prerelease: false
        files: ${{ inputs.files }}
