on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do release
        uses: ./
